apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk050-k8s-api
  namespace: sk050-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk050-k8s-api
  template:
    metadata:
      labels:
        app: sk050-k8s-api
    spec:
      containers:
        - name: sk050-k8s-api
          image: amdp-registry.skala-ai.com/skala26a-ai2/sk050-backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - secretRef:
                name: sk050-db-secret
            - configMapRef:
                name: sk050-k8s-api-config
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 18
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
