apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sk050-app
resources:
  - configmap/api-configmap.yaml
  - configmap/rag-configmap.yaml
  - secret/db-secret.yaml
  - deployment/api-deploy.yaml
  - deployment/fe-deploy.yaml
  - deployment/rag-deploy.yaml
  - service/api-service.yaml
  - service/fe-service.yaml
  - service/rag-service.yaml
  - ingress/ingress.yaml
