apiVersion: v1
kind: Secret
metadata:
  name: sk050-db-secret
  namespace: sk050-app
type: Opaque
data:
  DB_URL: bXlzcWwrYWlvbXlzcWw6Ly9za2FsYTpTcWxEYmEtMUAxNjguMTA3LjMxLjEzMjozMzA2L2FmdGVyX21pZ3JhdGlvbj9jaGFyc2V0PXV0ZjhtYjQ=
